### ISSUE TITLE
Getting Error While connecting to Redshift DB from Java using R?

### ISSUE THREAD

**Issue by VineelaKantamneni** [eugenp/tutorials#10887]
When I try to connect to Redshift DB from Rstudio it is successfully working.But when I try to execute same R script from Java using Rserve method getting Error like below.Please help me out to solve this.

My R script:

dir.create('~/.redshiftTools')
download.file('https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/2.0.0.4/redshift-jdbc42-2.0.0.4.jar','~/.redshiftTools/redshift-driver.jar')
driver <- JDBC("com.amazon.redshift.Driver", "~/.redshiftTools/redshift-driver.jar", identifier.quote="`")
url <- sprintf("jdbc:redshift://myurl", "host","port","dbname")
conn <- dbConnect(driver, url, "username", "password")

Java code:

        c.eval(" driver <- JDBC(\"com.amazon.redshift.Driver\", \"~/.redshiftTools/redshift-driver.jar\", identifier.quote=\"`\")");
        c.eval("url <- sprintf(\"jdbc:redshift://myurl", \"host\",\"port\",\"dbname\")");
        c.eval("conn <- dbConnect(driver, url, \"username\", \"password\")");

Java console Error:
Exception in thread "main" org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127
	at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:261)

Rstudio console Error:
   Error in JDBC("com.amazon.redshift.Driver", "~/.redshiftTools/redshift-driver.jar",  : 
  could not find function "JDBC"

>>>>Not getting any errors when I am running same code from Rstudio

**Comment by kwoyke** [comment]
Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.
