### ISSUE TITLE
Lock striping Java code might be flawed

### ISSUE THREAD

**Issue by Marcono1234** [eugenp/tutorials#12096]
It looks the Java code in the article https://www.baeldung.com/java-lock-stripping (respectively [this directory of the repository](https://github.com/eugenp/tutorials/tree/master/core-java-modules/core-java-concurrency-collections-2/src/main/java/com/baeldung/concurrent/lock)) might be flawed:
- The name of the parameter `int threads` is misleading.
The code uses [`CompletableFuture.supplyAsync(Supplier)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletableFuture.html#supplyAsync(java.util.function.Supplier)) which uses the common pool with a fixed number of threads. The parameter `threads` is rather a _task count divided by 4_.
- The usage of `Striped` with `HashMap` does not appear to be thread-safe.
`HashMap` is in general not thread-safe; trying to lock only certain areas of it with a striped lock can most likely not be thread-safe because even if two entries were placed in separate buckets, the map also has global state such as the total map size which has to be accessed in a thread-safe way. Besides that, it is unlikely that the current usage of the striped lock really matches how `HashMap` distributes the entries, especially when the map is rehashed when the capacity is increased during addition of new entries.
- The comparison is done with a `ConcurrentHashMap` with additional synchronization.
The experiment and benchmarking code seems to apply the locks to `ConcurrentHashMap` as well. This usage is rather weird and probably not close to reality because it is unlikely that one puts additional synchronization around `ConcurrentHashMap` usage. Instead it might be more interesting to see comparison between a striped lock implementation and direct `ConcurrentHashMap` usage (without any additional synchronization on it).

The idea of showcasing how Guava's `Striped` can be used and comparing it with another concurrent collection is really great, but for that `HashMap` should probably not be used due to the issues outlined above.

**Comment by jsgrah-spring** [comment]
Hi @kwoyke , @Marcono1234 ,

- The name of the parameter int threads is misleading.

The code uses [CompletableFuture.supplyAsync(Supplier)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletableFuture.html#supplyAsync(java.util.function.Supplier)) which uses the common pool with a fixed number of threads. The parameter threads is rather a task count divided by 4.

**I agree that the name of the parameter int thread is misleading and could be changed for taskTotal, tasks or totalNumberOfTasks as an example. ** 

The parameter threads is rather a task count divided by 4.
** It is indeed the total number of tasks divided by 4 slots, since every task in being run into 4 different slots **


The usage of Striped with HashMap does not appear to be thread-safe.
HashMap is in general not thread-safe; trying to lock only certain areas of it with a striped lock can most likely not be thread-safe because even if two entries were placed in separate buckets, the map also has global state such as the total map size which has to be accessed in a thread-safe way. Besides that, it is unlikely that the current usage of the striped lock really matches how HashMap distributes the entries, especially when the map is rehashed when the capacity is increased during addition of new entries.
**I do not agree on this one because the main point of using Striped is to enforce thread-safety, improve throughput as well as reducing memory footprint due to high locking contention where thread safety is non-existant, like in HashMap. **

The comparison is done with a ConcurrentHashMap with additional synchronization.
The experiment and benchmarking code seems to apply the locks to ConcurrentHashMap as well. This usage is rather weird and probably not close to reality because it is unlikely that one puts additional synchronization around ConcurrentHashMap usage. Instead it might be more interesting to see comparison between a striped lock implementation and direct ConcurrentHashMap usage (without any additional synchronization on it).
**I agree that applying Lock Stripping to ConcurrentHashMap is weird since ConcurrentHashMap already provides synchronization out-of-the-box. If one looks carefully at the benchmark results, it reveals that Lock Striping performs better when using HashMap than ConcurrentHashMap. ConcurrentAccessBenchmark.singleLockConcurrentHashMap vs ConcurrentAccessBenchmark.singleLockHashMap and ConcurrentAccessBenchmark.stripedLockConcurrentHashMap vs ConcurrentAccessBenchmark.stripedLockHashMap**

The idea of showcasing how Guava's Striped can be used and comparing it with another concurrent collection is really great, but for that HashMap should probably not be used due to the issues outlined above.
**I disagree with this one because the idea of showcasing Guava's Striped is not limited to accessing non-thread-safe collection like HashMap but also performing critical operations faster and with low memory footprint in a thread-safe manner**

I really wonder what to do next, since there is some very relevant points in the comment but some slightly less pertinent point too.

Thanks
Joseph

**Comment by dkapil** [comment]
Fixed the variable name, closing this one

**Comment by Marcono1234** [comment]
@jsgrah-spring, I do not agree with your assessment:

> because the main point of using Striped is to enforce thread-safety

Yes, but as explained previously, the code _is not thread-safe_. This can even be seen easily: Increase the number of tasks to e.g. 1000000 and then call `Map.size()` on the result of `doWork` and you will see a value smaller than 1000000, for example in my case 999974 (might have to run it multiple times). Or extend the code to check that the result from `getSupplier` actually matches the expected value, and you will notice that occasionally it returns `null`.

> it reveals that Lock Striping performs better when using HashMap than ConcurrentHashMap

Yes, but what is the point of that? The whole point of this article is to show that `Striped` can be used as alternative, but why then guard access to a `ConcurrentHashMap` with `Striped`? `ConcurrentHashMap` is already thread-safe, so you would not guard access to it with `Striped` to make it _more thread-safe_!? It would be much more interesting to compare performance of the `Striped` version with using directly a `ConcurrentHashMap` (without `Striped`).

Also, for what it's worth the example code in https://www.baeldung.com/java-lock-stripping#4-concurrent-access-with-striped does not compile because the field is erroneously named `lock` instead of `stripedLock` (the code in this repository is correct though).

**Comment by jsgrah-spring** [comment]
Hi @Marcono1234 ,

> Ref: because the main point of using Striped is to enforce thread-safety

I understand your point partially and not entirely: The main point of using Striped class from Guava is not to enforce thread-safety but **to achieve finer-grained concurrency** as opposed **to coarse-grained concurrency**. By doing that, Striped implicitly enforces thread-safety.  

The ConcurrentHashMap itself uses a striped locked approach to increase concurrency, to this regard, I totally agree with you that the comparison should NOT be made by applying a Lock-Striping to both a HashMap and a ConcurrentHashMap. 

> It would be much more interesting to compare performance of the Striped version with using directly a ConcurrentHashMap (without Striped).

I agree.

I will update the article and correct the field named lock instead of stripedLock.

Thanks
Joseph

**Comment by Marcono1234** [comment]
> By doing that, Striped implicitly enforces thread-safety.

Except that, as pointed out above, the way the example code uses `Striped` around a `HashMap` *is not thread-safe*. If you add 1,000,000 entries to a map and `Map.size()` afterwards returns 999,974 then that code is broken. And even if I weren't able to provide an example showing this[^1], my comment above that the internal `HashMap.size` field is being updated in a non-thread-safe way would still apply.

[^1]: In general proving that something is not thread-safe through an example can be difficult or in some cases impossible because thread-safety issues might only occur in one of million tries, but that nonetheless does not make the code thread-safe.

**Comment by konfilios** [comment]
I was just going through this tutorial and wanted to stress how important @Marcono1234 comments are. All of them.

You mention that "the point of striping is to provide thread safety". Indeed, but that's not automatic or magic. There are prerequisites, the most important being that the whole state of the data structure (in this case the hash map) being stripe-locked can be "striped".

If the "size" variable of the hashmap is not straightforward enough, consider the case of a hashmap expansion because it exceeded the initial capacity. This is a global change to the datastructure which comes from a single insert operation. That insert operation would only acquire one of the locks but changes to all buckets will take place.

Overall, stripe locks are suitable for providing fine locking to data structures that can be perfectly partitioned (or striped) themselves internally. If there is any internal state of the datastructure (fields, arrays, etc.) that spans across different stripes, especially during state mutation, then stripe locking does *not* provide thread safety.

I can't stress this enough: If someone seeks thread safety, then it means it's critical for their application. They *will* have multi-threaded access and/or mutation to the datastructure and they cannot afford inconsistent data. By advertising that a solution that will provide thread safety while it is guaranteed that it is not (which is the case with your example), then you're pushing people into a disaster of possibly hard to track bugs that come from their concurrent code.

**Comment by konfilios** [comment]
Btw I just found a good example on how lock striping can give you real thread safety

https://tech.trivago.com/post/2022-03-09-why-and-how-we-use-primitive-maps.html
