### ISSUE TITLE
Question about bulk update using mongoTemplate#bulkOps#updateMulti#execute

### ISSUE THREAD

**Issue by samucamarques** [eugenp/tutorials#12485]
Using this kind of implementation, will spring data care about OptmistickLock versioning?

**Comment by kwoyke** [comment]
Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.
Hope that makes sense.
