### ISSUE TITLE
Spring JPA @convert encryption and decryption

### ISSUE THREAD

**Issue by sheraliinamdar** [eugenp/tutorials#12497]
Hi , I am trying to implement pattern searching for encrypted columns. i am using spring jpa and MySQL database for column attribute encryption. It Seems like to implement pattern searching (i.e contains or like %) first we need to decrypt all records and then search the pattern which is performance bottleneck in case of lakhs of records. do we have any other approach where we can encrypt/Decrypt table columns and which should support pattern searching also for encrypted columns. Looking out for your help or suggestions ?

**Comment by kwoyke** [comment]
Hi,

Are you referring to any of our articles?

**Comment by sheraliinamdar** [comment]
Hi @kwoyke 
 It is with reference to https://www.baeldung.com/jpa-attribute-converters , if it is not possible to do pattern search, do we have any other approach to implement it ?

**Comment by ulisseslima** [comment]
Hey, @sheraliinamdar

Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.
Hope that makes sense.

Cheers,
Team
