### ISSUE TITLE
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype

### ISSUE THREAD

**Issue by jmjava** [eugenp/tutorials#12616]
i have a set of classes with some overlapping fields but none are exactly the same.  Parsing seems to work for some payloads but I get 

com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype

I tried to debug into the code and it looks like subtypeFingerprints contains an entry for each subclass and none of the entries contains the same values completely.  There are some common fields though.

I there anything i need to enable to get the code to look at all the fields or see the subclasses as unique?

thanks

**Comment by ulisseslima** [comment]
Hey @jmjava,

Unfortunately, we can only help with questions that are specifically and directly related to the articles - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.
I hope that makes sense.

Cheers,
Team
