### ISSUE TITLE
class org.springframework.security.authentication.UsernamePasswordAuthenticationToken cannot be cast to class CustomAuthenticationToken (org.springframework.security.authentication.UsernamePasswordAuthenticationToken and it.besmart.eshare.config.CustomAuthenticationToken are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @31221be2)

### ISSUE THREAD

**Issue by marioconforti** [eugenp/tutorials#12749]
In project [loginextrafieldscustom](https://github.com/eugenp/tutorials/tree/master/spring-security-modules/spring-security-web-login/src/main/java/com/baeldung/loginextrafieldscustom)

I have my CustomAuthenticationToken which extends UsernamePasswordAuthenticationToken as in the project.

Then, as in the project in CustomUserDetailsAuthenticationProvider we have the  retrieveUser method

` CustomAuthenticationToken auth = (CustomAuthenticationToken) authentication;`

In this part the application throws an exception:

`class org.springframework.security.authentication.UsernamePasswordAuthenticationToken cannot be cast to class it.besmart.eshare.config.CustomAuthenticationToken (org.springframework.security.authentication.UsernamePasswordAuthenticationToken and icon.xxx.xxx.xxx..CustomAuthenticationToken are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @31221be2)`

**Comment by ulisseslima** [comment]
Hey, @marioconforti.

Make sure your `CustomAuthenticationFilter` is correctly set up. It's the one responsible for converting the authentication request into a `CustomAuthenticationToken`.

You can check `LoginFieldsFullIntegrationTest` for a full test.

Also, you seem to be using code different from our repository. Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.
Hope that makes sense.
