### ISSUE TITLE
getParts return null with CachedBodyHttpServletRequest

### ISSUE THREAD

**Issue by MUedsa** [eugenp/tutorials#12958]
`super.request.inputStream` readed finish, `getParts()`&`getPart(name)` return null.

https://github.com/eugenp/tutorials/blob/3ee97b9426650f924579a384434fc8ecb733034e/spring-web-modules/spring-mvc-basics-3/src/main/java/com/baeldung/cachedrequest/CachedBodyHttpServletRequest.java#L15-L23

**Comment by ulisseslima** [comment]
Hey @MUedsa.

Can you please elaborate on the issue you're having?

Does this happen with the code in the repo for [this article](https://www.baeldung.com/spring-reading-httpservletrequest-multiple-times) or on your own code?

**Comment by MUedsa** [comment]
It will well work for `application/json` request(use `@RequestBoay` in Controller).
But `multipart/form-data` request, `@RquestPart` or `@RequestParam`  not use `HttpServletRequest.getInputStream` to resolve request body.

**Comment by ulisseslima** [comment]
Indeed, this article is intended specifically for `HttpServletRequest.getInputStream()`. Therefore, `multipart/form-data` is out of its scope, as it depends on what you're trying to do.

You could try receiving your request parameters as a map, so you won't need to use the `request` object multiple times: https://stackoverflow.com/questions/7312436/spring-mvc-how-to-get-all-request-params-in-a-map-in-spring-controller

But, again, that depends on your use case. Unfortunately, we can only help with questions that are specifically and directly related to the content of the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.

Hope that makes sense.
