### ISSUE TITLE
Fail to compile spring-cloud-modules/spring-cloud-hystrix/spring-cloud-hystrix-feign-rest-consumer

### ISSUE THREAD

**Issue by sawantdatta** [eugenp/tutorials#13605]
Issue in GreetingClient.java please check.

**Comment by ulisseslima** [comment]
Hey, @sawantdatta.

Considering this tutorial: https://www.baeldung.com/spring-cloud-netflix-hystrix

The module is building correctly. Make sure you import the `pom.xml` from `tutorials/spring-cloud-modules/spring-cloud-hystrix` instead of only the one on `tutorials/spring-cloud-modules/spring-cloud-hystrix/spring-cloud-hystrix-feign-rest-consumer` as it depends on the other modules.
