### ISSUE TITLE
unable to send HTTP post request to server over unix socket

### ISSUE THREAD

**Issue by rai-prashanna** [eugenp/tutorials#14186]
I have a REST API server that supports all kinds of HTTP operations like GET, POST, PUT, and DELETE operations. 
I have difficulty with consuming rest api like sending JSON data to REST api server without using any third party library like netty, 
With the new version of JAVA, I think it is possible to send POST requests over unix socket but I have no idea how it can be done. 
Any kind of help would be appreciated!

**Comment by ulisseslima** [comment]
Hi @rai-prashanna,

We have an article here on Unix Domain Sockets in Java 16 that may help: https://www.baeldung.com/java-unix-domain-socket

Unfortunately, we can only help with questions that are specifically and directly related to our articles - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.

Hope that makes sense.
