### ISSUE TITLE
jackson-simple unit test failed in window machine

### ISSUE THREAD

**Issue by wizdata** [eugenp/tutorials#14391]
at com.baeldung.jackson.objectmapper.ObjectMapperBuilderUnitTest.whenWri
teRequestObject_thenReturnRequestJsonStrCorrectly(ObjectMapperBuilderUnitTest.ja
va:42

**Comment by ulisseslima** [comment]
Hey, @wizdata.

Can you give more details?

Does `mvn clean install` work?

Can you include the complete stack trace with the error message?

**Comment by wizdata** [comment]
[INFO] Running com.baeldung.jackson.objectmapper.ObjectMapperBuilderUnitTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.129 s <<
< FAILURE! - in com.baeldung.jackson.objectmapper.ObjectMapperBuilderUnitTest
[ERROR] whenWriteRequestObject_thenReturnRequestJsonStrCorrectly  Time elapsed: 0.
127 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:
expected: <{
  "car" : {
    "color" : "White",
    "type" : "Sedan"
  },
  "datePurchased" : "2023-05-24 12:00 PM IST"
}> but was: <{
  "car" : {
    "color" : "White",
    "type" : "Sedan"
  },
  "datePurchased" : "2023-05-24 12:00 PM IST"
}>
        at com.baeldung.jackson.objectmapper.ObjectMapperBuilderUnitTest.whenWrite
RequestObject_thenReturnRequestJsonStrCorrectly(ObjectMapperBuilderUnitTest.java:4
2)

**Comment by wizdata** [comment]
Closed by accident

**Comment by ulisseslima** [comment]
Hey, @wizdata.

Thanks for the feedback. This issue will remain open until we fix this.

**Comment by dkapil** [comment]
@wizdata the issue is not specific to the machine but the formatter. We have used SimpleDateFormat to format date strings and it is expected that it will give consistent output. But, the output can change, specially the AM/PM strings in case of locales. For e.g. UK Locale will generate lower case am/pm, while US locale will generate uppercase AM/PM.

I have updated the article and the corresponding code to handle locale as well. https://www.baeldung.com/jackson-object-mapper-tutorial
