### ISSUE TITLE
Java Phaser Bug

### ISSUE THREAD

**Issue by austinarbor** [eugenp/tutorials#14528]
Hello,
I think there is a bug in the article https://www.baeldung.com/java-phaser

With the class

```java
class LongRunningAction implements Runnable {
    private String threadName;
    private Phaser ph;

    LongRunningAction(String threadName, Phaser ph) {
        this.threadName = threadName;
        this.ph = ph;
        ph.register();
    }

    @Override
    public void run() {
        ph.arriveAndAwaitAdvance();
        try {
            Thread.sleep(20);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        ph.arriveAndDeregister();
    }
}
```

And then the subsequent code

```java
executorService.submit(new LongRunningAction("thread-1", ph));
executorService.submit(new LongRunningAction("thread-2", ph));
executorService.submit(new LongRunningAction("thread-3", ph));
```

Doesn't this create a race condition between all of the `LongRunningAction` instances being instantiated (calling `ph.register`), and the `Executor` calling `run`, which calls `ph.arriveAndAwaitAdvance();` ?

If one of the tasks calls `ph.arriveAndAwaitAdvance()` before all 3 instances are instantiated, won't it advance before it is supposed to?

Thanks

**Comment by ulisseslima** [comment]
Hey, @austinarbor.

We'll look into this and update the article if necessary.

This issue will remain open until then.

**Comment by dkapil** [comment]
This will not create a race condition and it will not advance when tasks are instantiated because we are instantiating the phaser object with 1, this means registered party is already equal to one before other tasks are instantiated.

`ExecutorService executorService = Executors.newCachedThreadPool();`
`Phaser ph = new Phaser(1);`

The number of registered party here is 1, now when task is being instantiated like:

`executorService.submit(new LongRunningAction("thread-1", ph));`

After this line, the registered party increases to 2, but threads waiting at the barrier is still 1 which is called from the run method of this thread.

Similarly, when all three threads are instantiated:
`executorService.submit(new LongRunningAction("thread-1", ph));`
`executorService.submit(new LongRunningAction("thread-2", ph));`
`executorService.submit(new LongRunningAction("thread-3", ph));`

Here the current state is, registered parties =4, arrived at barrier =3, therefore execution is not triggered.
It only gets triggered when `ph.arriveAndAwaitAdvance();` at the next line.

Hope this helps.
Closing this issue.
