### ISSUE TITLE
@Transactional annotation in DDD with Spring

### ISSUE THREAD

**Issue by vigamage** [eugenp/tutorials#14661]
This question relates to the implementation described in below link.

[https://www.baeldung.com/hexagonal-architecture-ddd-spring](https://www.baeldung.com/hexagonal-architecture-ddd-spring)

As per the explanation there, we should isolate our domain layer from spring framework too. To follow that principal, even the spring bean configuration has been moved to the infrastructure layer.(`@service` annotation is not being used inside DomainOrderService)

Now my question is how can we use the `@Transactional` annotation ? Transaction should be managed from the service layer and for that we have to use the annotation in `DomainOrderService`. But it will break the above mentioned isolation principal. 

What options do we have here?

**Comment by ulisseslima** [comment]
Hey, @vigamage.

One option could be: instead of using Spring's `@Transactional`, define a custom annotation like `@BusinessTransactional` to mark methods that should be transactional. Then, using AOP, create an aspect that ties your custom annotation to the actual transaction management. This approach clearly distinguishes between business operations that need transactions and other technical transactions.

It's also crucial to understand that while Hexagonal Architecture and DDD provide excellent guidelines and principles, there will always be certain trade-offs to consider. Sometimes, it might be more pragmatic to "break" the pure isolation for clarity, simplicity, or performance.

Unfortunately, we can only help further with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions, like this one: https://stackoverflow.com/questions/59548612/hexagonal-architecture-and-transactions-concept.

That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.

Hope that makes sense.
