### ISSUE TITLE
[QUESTION] Not finding FacesInitializer

### ISSUE THREAD

**Issue by pitdelling** [eugenp/tutorials#15594]
Hello Baeldung's team, how are you?

I'll start saying I love your job. All the articles are super detailed, explanatory and helpful. Thanks for it. All your work make our developer's lives better!

But I'm here today because of this line:

https://github.com/eugenp/tutorials/blob/5557d42322c5733f3a3dfa96d9db4b49a111039f/web-modules/jsf/src/main/java/com/baeldung/springintegration/config/MainWebAppInitializer.java#L14C44-L14C61

I'm trying to use JSF with Spring MVC, and your recent implementation + article comes helping me. But I can't find a way to extends the FaceInitializer class as you do on that line I pasted here. Could you post the print from your code, where it is camming from, please?

![image](https://github.com/eugenp/tutorials/assets/16709062/b3d19a48-c707-4f88-b396-cd94f4d77009)

**Comment by ulisseslima** [comment]
Hey, @pitdelling.

We're assuming this is the tutorial you were following: https://www.baeldung.com/spring-jsf

Since you're using Eclipse, if you import the original project and press F3 on the `FacesInitialzer` class from the `MainWebAppInitializer` class, you'll see that it comes from the `jsf-impl` dependency.

Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.

Hope that makes sense.

**Comment by pitdelling** [comment]
Perfect, I understand. Thanks for your help
