### ISSUE TITLE
Customizing Token Storage in spring security oauth2 client

### ISSUE THREAD

**Issue by cdwijayarathna** [eugenp/tutorials#16469]
Apologies in advance if this is not the right place to raise this query. I am following the tutorial [here](https://www.baeldung.com/spring-cloud-gateway-bff-oauth2) for implementing backend for frontend model for oauth2 using the `spring-addons-starter-oidc`. How can I customize the tokenStorage that the bff uses to store the tokens?

Also, can I use a client side session as specified in the [IETF draft](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps-17) and use an encrypted version of token as the session cookie rather than an opaque session ID?

**Comment by apeterlic** [comment]
Hey @cdwijayarathna,

Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.
Hope that makes sense.

Cheers,
Team
