### ISSUE TITLE
[ISSUE] In DDD design can we use @Transactional ? if we use the same,  it will become technology specific?

### ISSUE THREAD

**Issue by talasila66** [eugenp/tutorials#16928]
[tutorials](https://github.com/eugenp/tutorials/tree/master)/[patterns-modules](https://github.com/eugenp/tutorials/tree/master/patterns-modules)
/ddd

In DDD design can we use @Transactional ? if we use the same,  it will become technology specific?

**Comment by apeterlic** [comment]
Hey, @talasila66

Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions, like this one: https://stackoverflow.com/questions/59548612/hexagonal-architecture-and-transactions-concept.

That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.

Hope that makes sense.
