### ISSUE TITLE
Why is MILE an allowed JSON literal value in the serialization of the Distance enum? 

### ISSUE THREAD

**Issue by XSven** [eugenp/tutorials#1753]
Hi Eugen,

according to item 6. of

[jackson-serialize-enums](http://www.baeldung.com/jackson-serialize-enums)

the serialization of the Distance enum equals

{"name":MILE,"unit":"miles","meters":1609.34}

According to JSON RFC 7159 the only literal values in JSON are false, null, true.

It seems that MILE is a literal in the above serialization?! Could you please explain this to me.

Thx and kind regards
Sven

**Comment by sunilmogadati** [comment]
Hi @XSven, this seems to be because in the code, _generator.writeNumber(distance.name())_ is used instead of _generator.writeString(distance.name())_. 
Here is the [pull request](https://github.com/eugenp/tutorials/pull/1763/files). The article is also getting updated. 
Please let know if this answers your question.

**Comment by XSven** [comment]
Yes that answers my question but why does the Jackson framework doesn't hinder the end user to create invalid JSON documents?

**Comment by eugenp** [comment]
That's an interesting question Sven, but it may be better targeted on the support forum of the library itself in this case. 
Cheers, 
Eugen.
