### ISSUE TITLE
Do you know why server requesting username and password?

### ISSUE THREAD

**Issue by pashtika** [eugenp/tutorials#250]
When I deployed the application and trying to launch: http://localhost:8080/spring-security-rest-full/    its asking me username and password to enter. I enter credentials looking at
`<user name="user1" password="user1Pass" authorities="ROLE_USER"/>`, but it's giving error

`web - 2015-09-17 01:16:30,835 [http-bio-8080-exec-6] WARN  o.s.web.servlet.PageNotFound - No mapping found for HTTP request with URI [/spring-security-rest-full/] in DispatcherServlet with name 'api'`

![full_rest](https://cloud.githubusercontent.com/assets/8208031/9916437/f4a3c2f0-5cd9-11e5-8afb-12ec42396ae5.png)

**Comment by eugenp** [comment]
That's because the URL you're using - `http://localhost:8080/spring-security-rest-full/` - isn't complete - there's nothing mapped at the root level. So - you'll need to actually hit one of the existing mappings - for example: `http://localhost:8080/spring-security-rest-full/foos/count`
Also, remember - this tutorial project, like many of the others in this repo - is simply to illustrate some specific concept from an article - so these aren't a fully functional API. The REST project here on github is a much more complete one if you need a good base. 
Hope that helps. Cheers, 
Eugen.
