### ISSUE TITLE
cvc-complex-type.3.2.2: Attribute 'access-denied-page' is not allowed to appear in element 'http'.

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#348]
I'm using spring-jpa project without any customization yet and trying to compile the code, but its giving following error:

Could you please address to this issue?
cvc-complex-type.3.2.2: Attribute 'access-denied-page' is not allowed to appear in element 'http'.

**Comment by eugenp** [comment]
Not sure why you're running into that issue - I'm able to fully build the project with no errors. However, just to be on the safe side, I removed the file that was likely leading you to that problem - because it wasn't in use anyways. 
If you still have issues building the project, let me know. Cheers, 
Eugen.
