### ISSUE TITLE
@Value example for MAP type

### ISSUE THREAD

**Issue by snaimat** [eugenp/tutorials#3560]
Hi,
I see you have some good basic examples of @value converting to objects.  I wanted to see an example for converting to a map type. 

for e.g. 

sodaCanColorMap={Coke:Red,Pepsi:Blue,LaCroix:Clear}

@Value("#{'${sodaCanColorMap}'.split(',')}") --> gives a List<String> 

How can I load the values straight into a MAP<String,String>

Thanks,

Sadfeen.

**Comment by eugenp** [comment]
Hey @snaimat - that's a very interesting question. I'm assuming you're reading this article here: 
http://www.baeldung.com/spring-value-annotation

I'll have a look into it and we may add a new section to that article, talking about how to handle this scenario. 
But, before that, let me also say that the best way to ask this is over on StackOverflow, instead of an issue here (since this is not really an issue with the code here). 
You can email me the link, and I'll have a look. 

Cheers, 
Eugen.
