### ISSUE TITLE
Autowire more dependency's is not possible?

### ISSUE THREAD

**Issue by janoshh** [eugenp/tutorials#3703]
I want to mock the restTemplate in a integration test, when i follow the example it is working fine but it is not really the case i want to test. For starters my call is private and called in an other method. Second problem is that the method is executed by a scheduler. So my test case: A method is called by a scheduler, next is the a get request  (with restTemplate, I want to mock this one), the response should save some data in a repository and publish an event on a queue. Is there a workaround for this case?

**Comment by eugenp** [comment]
Hey @janoshh - thanks for reaching out - that looks like an interesting scenario you're working on. 
Unfortunately, it's also an unrelated scenario - as you mentioned - the codebase here is working fine. 
And so, this needs to be a question over on StackOverflow, instead of an issue here. 
Feel free to email me the link to the question, and I'll try to help if the community doesn't get to it first. 

Cheers, 
Eugen.
