### ISSUE TITLE
SLFJ error during unit and integration testing

### ISSUE THREAD

**Issue by Thoughtscript** [eugenp/tutorials#3821]
Encountered: while debugging and testing in Jetbrains IDE - specifically in the `libraries` module while adding a sub-module for OpenCSV:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Adam%20Gerard/.m2/repository/org/slf4j/slf4j-log4j12/1.7.7/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Adam%20Gerard/.m2/repository/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
SLF4J: org.apache.commons.beanutils.converters.BooleanConverter
```

This is not a critical error - it's a warning - tests pass and it involves the existing pom.xml configuration for logging.  Just curious what the cause of this might be, how to fix it, and/or improve my future logging in test cases or logging blocks.

This is out of scope for the specific issue I'm on and I don't want to break the existing 20+ library examples included in that directory!

I will also dive into this when I have more time. Thank you!

**Comment by lor6** [comment]
Hey Adam,
As you probably know slf4j is an abstraction for other logging libraries like logback and log4j. The warning is caused by two different implementations being present on the classpath: once from the logback-classic library and once from the slf4j-log4j library. 

Now, if you look in the pom.xml neither of these is explicitly added, and they are even excluded a few times. But since there are so many libraries in the project, a few of them bring in both of these libraries transitively.

The solution would be to exclude one of them from the other libraries so that only one slf4j logging implementation remains. But in this case, that doesn't seem worth it.

The warning essentially means that when you use slf4j API and not a more specific API, and have more than one implementation in the classpath, then slf4j will pick one of the available implementations at random.

You can read more about the issue on the slf4j website: https://www.slf4j.org/codes.html#multiple_bindings
