### ISSUE TITLE
spring-security-sso

### ISSUE THREAD

**Issue by stereo720712** [eugenp/tutorials#4176]
Execuse me :
When I try this example , I find a problem:
redriect_uri will disappear when i use  a custom domain name
like this:
http://sso.npi.foxconn.com:8091/auth/oauth/authorize?client_id=ClientId&redirect_uri=http:/ui/login&response_type=code&state=MIRylZ

But when use ip or localhost , it is correct
http://sso.npi.foxconn.com:8091/auth/oauth/authorize?client_id=ClientId&redirect_uri=http://localhost:8081/ui/login&response_type=code&state=xhgYRH
Can anyone tell me how to slove this problem

**Comment by lor6** [comment]
Hey @stereo720712 

It's difficult to say. The redirect_uri by default should be the current uri of your client. I suggest checking the network traffic to see where it's lost. The client should first send a request to /ui/login and get back a 302 response with a Location header that contains the address of the oauth server endpoint to call along with the redirect_uri parameter. Have a look to see if it's set correctly from the client.

You can control the redirect_uri of the client by setting properties:
security:
  oauth2:
    client:
      registered-redirect-uri: http://custom-host:8082/ui/login
      pre-established-redirect-uri: http://custom-host:8082/ui/login
      use-current-uri: false

But to see why it's not working by default, you'll have to do some debugging through Spring.

If the above doesn't help, I suggest posting a question on stackoverflow with more details. Feel free to send an email to team@baeldung.com with the link and we'll try to have a look.

Since this isn't an issue with our repository, I'll close this.
