### ISSUE TITLE
JPA Specifications is not international

### ISSUE THREAD

**Issue by GuiRitter** [eugenp/tutorials#4341]
Hi everyone.

In [REST Query Language with Spring Data JPA Specifications](http://www.baeldung.com/rest-api-search-language-spring-data-specifications), besides the pattern still being `"(\w+?)(:|<|>)(\w+?),"` instead of `"(\\w+?)(:|<|>)(\\w+?),"`, `\\w` only works for English systems. For systems with more complex languages, `\\p{L}` should be used instead.

Also, things like `,` and ` ` in the search pattern breaks the matcher and causes all possible entries to be returned.

**Comment by lor6** [comment]
Hey @GuiRitter  Thanks, I've updated the article with \\w. For other systems, looks like the Pattern class has a UNICODE_CHARACTER_CLASS flag. I've added a mention of how to use this in the article, but I think the code is sufficient as-is for an example implementation. Using special characters would also involve changing the collation for the string parameter sent to the database and I'm not aware of any way to do that with JPA Criteria.

The pattern seems to work fine with the comma, though. Can you clarify on that?

Thanks.

**Comment by lor6** [comment]
@GuiRitter Thanks.
I've added a warning and suggestions in the article.

**Comment by GuiRitter** [comment]
Thanks for the updates and sorry to bother you again, but I'm having a hard time to integrate the between quotes pattern with the advanced search operations described [here](http://www.baeldung.com/rest-api-query-search-language-more-operations) and [here](http://www.baeldung.com/rest-api-query-search-or-operation).

I tried a few combinations but either all or no entities return.

Also, in [this](http://www.baeldung.com/rest-api-query-search-language-more-operations) article `\w` is still being used instead of `\\w`.

**Comment by lor6** [comment]
@GuiRitter Well, sure, you'll have to adapt the pattern to each type of search you want to be able to enter.
For example, for the /user/spec request, you could use a pattern like having the term in quotes surrounded by the punctuation marks, eg: search=firstName:*"jo"*,age<*"30"*

A pattern like this could work:
 Pattern pattern = Pattern.compile(
            "(\\w+?)(" + operationSetExper + ")(\\p{Punct}?[^\"])(\"\\w+?\")(\\p{Punct}?),");
where then you'd have to strip the quotes from the matcher.group(4) which is the seach term.

Or you could go with other formats to include that pattern.

Now since this isn't an issue in our code and the cases it's meant to support, I'll close this.
Cheers.
