### ISSUE TITLE
load testing tool comparison scripts are not like for like

### ISSUE THREAD

**Issue by ceeaspb** [eugenp/tutorials#5784]
Hi,
The Gatling script includes a 1 second pause between each request.

eg.
https://github.com/eugenp/tutorials/blob/master/testing-modules/load-testing-comparison/src/main/resources/scripts/Gatling/GatlingScenario.scala#L27

The other 2 don't have any pauses that I can see.

Suggest that either remove the 1 second pause from the Gatling script or add it to the other 2 scripts.

The difference in the scripts explains some of the differences in your test results esp. around peak throughput.

Thanks

**Comment by eric-martin** [comment]
Thanks @ceeaspb . We are investigating.

**Comment by eric-martin** [comment]
@ceeaspb This limitation is explicitly called out in the article:

"Here, we’ll pick up the reward id and save it to Gatling’s internal state. Notice the one-second pause, this necessary check prevents the next dependent request from failing. The check call and saveAs did not block subsequent exec requests."

So while the pause was intentional, the peak-throughput was de-emphasized in the overall result.
