### ISSUE TITLE
Neuroph Network gives wrong answers

### ISSUE THREAD

**Issue by Stallinator** [eugenp/tutorials#6247]
Hey, I tried following the tutorial at https://www.baeldung.com/neuroph.
After finishing I ran your integration Test "XORIntegrationTest". But the Network didn't work properly. So I copy pasted the whole code ad still the answers are wrong. 
This is the answer of the Network: 
Testing: 1, 0 Expected: 1.0 Result: 0.0
Testing: 0, 1 Expected: 1.0 Result: 0.0
Testing: 1, 1 Expected: 0.0 Result: 0.0
Testing: 0, 0 Expected: 0.0 Result: 0.0
But it should be
Testing: 1, 0 Expected: 1.0 Result: 1.0
Testing: 0, 1 Expected: 1.0 Result: 1.0
Testing: 1, 1 Expected: 0.0 Result: 0.0
Testing: 0, 0 Expected: 0.0 Result: 0.0

**Comment by Thoughtscript** [comment]
Hi! @Stallinator! I'm the original author of the article! Thanks for checking it out. I've gone ahead and tested this again in light of your issues. 

![capture](https://user-images.githubusercontent.com/10905039/52029707-44a1ed80-24c9-11e9-8d0a-409e5b9a9f16.PNG)
![capture2](https://user-images.githubusercontent.com/10905039/52029704-44a1ed80-24c9-11e9-8184-f2f5b15afecd.PNG)
![capture3](https://user-images.githubusercontent.com/10905039/52029705-44a1ed80-24c9-11e9-8e3c-5dbd4d2cbb26.PNG)
![capture4](https://user-images.githubusercontent.com/10905039/52029706-44a1ed80-24c9-11e9-9a60-fe25b9a9fe6f.PNG)

I took the liberty of moving the exact file out of the repo and running in an isolated app. You should be able to run it in the same way. You can also usually run `mvn install` on each of the modules but that can be a longer process since it involves pulling all the dependencies and going through all tests, etc. The code tested is the same used in the article. Please let me know if you have any other questions or if I missed something here!
