### ISSUE TITLE
Olingo Tutorial Error: Jersey Config No default constructor found

### ISSUE THREAD

**Issue by ajordaan** [eugenp/tutorials#7452]
Trying to follow the olingo tutorial (https://www.baeldung.com/olingo) but getting an error in the JerseyConfig.java class:

  Failed to instantiate [org.baeldung.examples.olingo2.JerseyConfig]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.baeldung.examples.olingo2.JerseyConfig.<init>()

 If I add a default constructor then the project builds successfully but does not work.

**Comment by psevestre** [comment]
Hi, @ajordaan 

Can you share a little bit more about your test environment ? 

JerseyConfig is a sprint @Component, so it should use its constructor as-is **in a Spring app** . Please note that this particular class is supposed to be used in the context of a springboot app. It seems it's been picked by Jersey directly, which indeer requires a no-arg constructor.

If you want to go ahead and use it this way, them you'll need to change this class in order to inject its dependencies using some other way (eg, CDI).

Otherwise, you should be able to run the sample using the following command sequence:

```
mvn clean
mvn package spring-boot:repackage
java -jar target/olingo2-sample-0.0.1-SNAPSHOT.jar
```

Please let us know if you're still facing issues running the sample code.
