### ISSUE TITLE
mvn clean install without a profile does not do a full build

### ISSUE THREAD

**Issue by sniffertine** [eugenp/tutorials#8189]
In the main readme, it states this: 
> To do the full build, do: mvn clean install

I do not get this to work. I needed to analyse the pom to see that I need to activate profiles.

Also it sais
> To build a specific module run the command: mvn clean install in the module directory

I was not able to do this (with an empty maven repo). Missing dependencies. I used this project: spring-remoting/remoting-amqp/remoting-amqp-client

**Comment by maibin** [comment]
@dkapil could you look into that please?

**Comment by eugenp** [comment]
Quick ping here, @maibin

**Comment by dkapil** [comment]
Hi @sniffertine 
We have updated our Readme with the latest instructions on how to build the repository and its specific modules.
For another issue, `remoting-http-client` is using a dependency `remoting-http-api`, which is itself present as a child project inside `spring-remoting\remoting-http\remoting-http-api`
Therefore for such child projects, we should be building the parent project first i.e. `spring-remoting` so that all the needed dependencies are available.

Hope this helps
