### ISSUE TITLE
spring-boot-springdoc: Is there any way if we can pass the Custom Header in all the request and train REST endpoints to accept that?

### ISSUE THREAD

**Issue by javaHelper** [eugenp/tutorials#8563]

**Comment by kwoyke** [comment]
Hi @javaHelper,
This seems to be an interesting case. However, with this kind of open questions, it's better to discuss it over e-mail - team@baeldung.com.
This is because here, on GitHub, we want to handle only the real issues directly related to our code base.
Just drop us an e-mail and we'll try to help.
