### ISSUE TITLE
(spring-data-elasticsearch) Integration Tests should call putMapping after index delete/create calls

### ISSUE THREAD

**Issue by chriswhite199** [eugenp/tutorials#883]
In the integration tests, the `@Before` annotated `before` method deletes and re-creates the index prior to each test. This fails to ensure the index mappings for each `@Document` object is correctly set (it is correctly set when the repository is created, but then lost in the `deleteIndex` call)

For others using your code as a starting point, you should explicitly call the `putMapping` method after the `createIndex` to ensure they don't get odd results from field mappings they have set, but don't appear to take hold in their integration tests

```java
    @Before
    public void before() {
        elasticsearchTemplate.deleteIndex(Article.class);
        elasticsearchTemplate.createIndex(Article.class);

        // ensure mappings are correctly set too
        elasticsearchTemplate.putMapping(Article.class);
```

**Comment by eugenp** [comment]
Hey @lor6 - let's see if this one is still relevant (I think it may not be). 
Thanks, 
Eugen.

**Comment by lor6** [comment]
In the [ElasticSearchQueryIntegrationTest](https://github.com/eugenp/tutorials/blob/master/spring-data-elasticsearch/src/test/java/com/baeldung/spring/data/es/ElasticSearchQueryIntegrationTest.java#L63) the putMapping() method is added after creating the index to add the mappings as well.

In the [ElasticSearchIntegrationTest](https://github.com/eugenp/tutorials/blob/master/spring-data-elasticsearch/src/test/java/com/baeldung/spring/data/es/ElasticSearchIntegrationTest.java) the putMappings() method is no present in order to test the default mappings.
