### ISSUE TITLE
Could not initialize class org.jetbrains.kotlin.gradle.internal.KotlinSourceSetProviderImplKt

### ISSUE THREAD

**Issue by GustaveNimant** [eugenp/tutorials#8955]
Hello

I followed the steps given in https://www.codeflow.site/fr/article/kotlin-javascript 
I answered "1 basic" for gradle init (which was not specified)
I copy the file https://github.com/eugenp/tutorials/blob/master/kotlin-js/src/main/kotlin/com/baeldung/kotlinjs/CryptoRate.kt and put it into src/main/kotlin
running gradle build gives the error "Could not initialize class org.jetbrains.kotlin.gradle.internal.KotlinSourceSetProviderImplKt"

What I did wrong ?

**Comment by lor6** [comment]
Hi @GustaveNimant  The original article is available here: https://www.baeldung.com/kotlin-javascript For the issue, is that reproducible on our codebase?

**Comment by kwoyke** [comment]
Hi @GustaveNimant,
Can you please clarify whether the issue occurs on our codebase as well - https://www.baeldung.com/kotlin-javascript?

**Comment by lor6** [comment]
Hi @GustaveNimant  This happens if the Kotlin version in the package.json doesn't match the one in the build.gradle file. Since the package.json is generated by nmp, you should then update the build.gradle file to match the versions.

I've upgraded the version in the code, and updated the original article: https://www.baeldung.com/kotlin-javascript
