### ISSUE TITLE
Error while getting token

### ISSUE THREAD

**Issue by ObiWanKaplan** [eugenp/tutorials#9164]
I've created an UAA server and a client, as shown in https://www.baeldung.com/cloud-foundry-uaa  
Now, I'm trying to login with my created user, after choosing rights and clicking "Authorize" I get this error: [invalid_id_token] An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found 
uaa.yml is attached below

![изображение_viber_2020-04-22_12-43-49](https://user-images.githubusercontent.com/37581258/79970100-dc637100-84ab-11ea-9665-246ca4226b8a.jpg)

[uaa.txt](https://github.com/eugenp/tutorials/files/4515435/uaa.txt)

**Comment by kwoyke** [comment]
Hi @ObiWanKaplan,
That's interesting.
Actually I wasn't able to run the full application due to some different problem (java.lang.IllegalArgumentException: Could not resolve placeholder 'encryption.active_key_label' in value "${encryption.active_key_label}")

Anyway, I see one potential problem in the uaa file you've attached. Below part is not properly formatted:
`   jwt:
  token:
    signing-key:`
The jwt indention is wrong. Here's how it should look like:
`
s
s
s
`

**Comment by kwoyke** [comment]
Hi @ObiWanKaplan,
Please let us know if the problem really lied in the wrong formatting.

**Comment by ObiWanKaplan** [comment]
Thanks, @kwoyke 
Actually, token is creating, but it can't be decoded, so I can't see it in browser - this problem I didn't solve. But I've created another app as a client and successfuly fetched this token using ScribeJava library.
