### ISSUE TITLE
`new CustomFilter()` in many places could be replaced with ApplicationContext.getBean

### ISSUE THREAD

**Issue by wattdave** [eugenp/tutorials#9474]
I made a beginner mistake that cost me time, and I think your tutorials could help. I added @Autowired and other configuration annotations to a custom filter I was trying to write based on one of your security examples. I then tried to new it up to connect it, as you do in your example here: (https://github.com/eugenp/tutorials/blob/d94ead72497f28c6a75f517a5020185d325054ba/spring-security-modules/spring-security-rest-basic-auth/src/main/java/com/baeldung/filter/CustomWebSecurityConfigurerAdapter.java), and I got a bunch of null pointer exceptions, because the @Autowired properties weren't wired up. It took calling AuthenticationContext.getBean(CustomFilter.class) to get the properties wired up properly. 

My mental model of Spring Boot improved once I figured that out. Might be worth it to put that in the examples to make that point clearer.

**Comment by lor6** [comment]
Hi @wattdave It's difficult to tell what the issue was in your example; you may have been trying to auto-wire some properties in the custom filter class, but the class itself wasn't registered as a bean or scanned. 

Your suggestion is valid, but it's an uncommon approach. I suggest having a look at component scanning: https://www.baeldung.com/spring-component-scanning and bean annotations: https://www.baeldung.com/spring-bean-annotations to understand how beans are created.
