### ISSUE TITLE
Updated Password policy will be changed to configurations added in uaa.yml file after restarting uaa tomcat. 

### ISSUE THREAD

**Issue by ShilpaVKulkarni** [eugenp/tutorials#9522]
Hi All,

I have used update identity provider api(https://docs.cloudfoundry.org/api/uaa/version/74.21.0/index.html#update) to update the password policy.
It worked for me. But if I restart my uaa tomcat then the password policy will be changed to configurations added in uaa.yml. Why the settings will change?Can anyone please provide solution for this?

Thanks & Regards
Shilpa Kulkarni

**Comment by lor6** [comment]
@ShilpaVKulkarni  Most likely this is the intended behavior, as the uaa.yml file is read again on starting the server. So you'll have to change the value there so that it's permanent.
But if this is not an issue with one of our tutorials, please raise this with the UAA project: https://github.com/cloudfoundry/uaa

Cheers.
